workflows:
  android-workflow:
    name: Flutter Android Build
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - firebase
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Setup Firebase google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
