workflows:
  android-workflow:
    name: Flutter Android Build
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - firebase
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter Analyze
        script: |
          flutter analyze
      - name: Setup Firebase google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      - name: Install Shorebird
        script: |
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | sh
      - name: Build with Shorebird
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          echo "Mencoba membuat update OTA (Patch)..."
          if ! shorebird patch android --force; then
            echo "Patch gagal (kemungkinan karena versi ini belum pernah dirilis). Membuat Release baru..."
            shorebird release android --force
          fi
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
